spring.application.name=LeaningRestApi
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
jwt.secret_key=${SECRET_KEY}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.data.redis.url=${REDIS_URL}
google.client.id=${GOOGLE_CLIENT_ID}
project.frontendURL=${FRONTEND_URL}
cloudinary.cloudName=${CLOUD_NAME}
cloudinary.apiKey=${CLOUD_KEY}
cloudinary.apiSecret=${CLOUD_SECRET}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
firebase.service-account-path=firebase-service-account.json
firebase.vapid-key=${VAPID-KEY}
